### ISSUE TITLE
打开酷安，首页加载过程中会闪退，必闪

### ISSUE THREAD

**Issue by TushningJJ** [Xposed-Modules-Repo/org.hello.coolapk#10]
可能是酷安改了什么东西，昨天还好好的

----part 5 start----
[ 2022-11-04T08:55:46.148        0:   754:  1491 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/verbose_2022-11-04T08:55:46.148.log
[ 2022-11-04T08:55:48.494        0:   754: 22024 I/LSPosedLogcat   ] !!refresh_modules!!
[ 2022-11-04T08:55:48.495        0:   754:  1491 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/modules_2022-11-04T08:55:48.495.log
[ 2022-11-04T08:55:51.743    10212: 19212: 19212 I/LSPosed         ] Loading xposed for com.coolapk.market/10212
[ 2022-11-04T08:55:51.745    10212: 19212: 19212 I/LSPosed-Bridge  ] Loading module org.hello.coolapk from /data/app/~~pb-XtZYA59nF5Vz1YS4K-w==/org.hello.coolapk-MQZTRrSfyAijH9IyTC4ehg==/base.apk
[ 2022-11-04T08:55:51.760    10212: 19212: 19212 I/LSPosed-Bridge  ]   Loading class org.fuck.coolapk.XposedEntry
[ 2022-11-04T08:55:52.712    10212: 19212: 19212 I/LSPosed-Bridge  ] FuckCoolApk: {removeBottomNavigationItems=false, bannerAuto=true, wlimits=v1RnVja0Nvb2xhcGtSXTAxd2pOQHJjfkB5THN1NHwkMmEkMTAkNmMxY2Y4OGNmN2M5ZWI2ZjY1YzYwdUNERnFENUxRVzFXNGEuZGF6VFl3OHJLLkcwYng3eEN8TkRJNE1UZzVOalV5TkRZek16azJPUT09, removeBannerAds=true, bannerUrl=https://316.coolapk1s.com, customCard=, removeFeedAdsEnhance=true, disableUmeng=true, bannerPic=https://cdn.jsdelivr.net/gh/ejiaogl/FuckCoolapk@master/art/316/316-2.png, removeFeedAds=true, disableBugly=true, removeSearchActivityItemHotSearchListCard=true, redirectLink=www.coolapk.com, timestamp=1667523032, checkFeedStatus=true, bannerForced=false, removeSearchActivityItemHotSearch=true, removeBottomNavigationDiscovery=false, removeSearchBoxHotWord=true, bannerEnable=true, removeFeedGoods=true, removeShareLinkParams=true, modifyShareUrl=false, removeUpdateDialog=true}
[ 2022-11-04T08:55:53.245    10212: 19212: 19212 I/LSPosed-Bridge  ] FuckCoolApk: CustomRuleConfig.getAll() theList = [CustomRule(entityType=null, title=小游戏, extraData=null, url=https://www.coolapk.com/link/sdw?sdw_simple=, entityTemplate=null, entities=null), CustomRule(entityType=null, title=双11, extraData=null, url=/feed/40241528, entityTemplate=null, entities=null), CustomRule(entityType=null, title=冲锋衣, extraData=null, url=/feed/40355595, entityTemplate=null, entities=null)]
[ 2022-11-04T08:55:53.254    10212: 19212: 19212 I/LSPosed-Bridge  ] FuckCoolApk: Class BeiZi not found
[ 2022-11-04T08:55:53.254    10212: 19212: 19212 I/LSPosed-Bridge  ] FuckCoolApk: Class BeiZis not found
[ 2022-11-04T08:55:53.423    10212: 19212: 19212 I/LSPosed-Bridge  ] FuckCoolApk: DexKit CheckUpdateMethod found: com.coolapk.market.CoolMarketApplication.ށ
[ 2022-11-04T08:55:53.463    10212: 19212: 19212 I/LSPosed-Bridge  ] FuckCoolApk: DexKit FeedBuildDialogMethod found: ז.ވ.Ԫ
[ 2022-11-04T08:55:53.496    10212: 19212: 19212 I/LSPosed-Bridge  ] FuckCoolApk: DexKit ReplyBuildDialogMethod found: ࡅ.ؠ.Ԩ
[ 2022-11-04T08:55:53.504    10212: 19212: 19212 I/LSPosed-Bridge  ] FuckCoolApk: rough_draft_backups path: /storage/emulated/0/Android/data/com.coolapk.market/files/rough_draft_backups
[ 2022-11-04T08:55:53.507    10212: 19212: 19212 I/LSPosed-Bridge  ] FuckCoolApk: rough draft listener started
[ 2022-11-04T08:55:53.959    10212: 19212: 19212 I/LSPosed-Bridge  ] FuckCoolApk: Current activity: class com.coolapk.market.view.main.MainActivity
[ 2022-11-04T08:55:54.169    10212: 19212: 19414 I/LSPosed-Bridge  ] FuckCoolApk: getInstalledPackages rejected
[ 2022-11-04T08:55:54.997    10212: 19212: 19212 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at Τ.ࢺ.އ(IconButtonGridCardViewHolder.kt:4)
	at com.coolapk.market.view.cardlist.EntityListFragment$֏.Ԩ(EntityListFragment.kt:2)
	at ذ.Ϳ.Ԫ(BaseMultiTypeAdapter.kt:1)
	at ذ.Ϳ.onBindViewHolder(BaseMultiTypeAdapter.kt:2)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:1)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:8)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:7)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:55)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:2)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:3)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:65)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:3)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:18)
	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1152)
	at android.view.Choreographer.doCallbacks(Choreographer.java:918)
	at android.view.Choreographer.doFrame(Choreographer.java:828)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1137)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8307)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
[ 2022-11-04T08:55:54.997    10212: 19212: 19212 E/AndroidRuntime  ] FATAL EXCEPTION: main
Process: com.coolapk.market, PID: 19212
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at Τ.ࢺ.އ(IconButtonGridCardViewHolder.kt:4)
	at com.coolapk.market.view.cardlist.EntityListFragment$֏.Ԩ(EntityListFragment.kt:2)
	at ذ.Ϳ.Ԫ(BaseMultiTypeAdapter.kt:1)
	at ذ.Ϳ.onBindViewHolder(BaseMultiTypeAdapter.kt:2)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:1)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:8)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:7)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:55)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:2)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:3)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:65)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:3)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:18)
	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1152)
	at android.view.Choreographer.doCallbacks(Choreographer.java:918)
	at android.view.Choreographer.doFrame(Choreographer.java:828)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1137)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8307)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
[ 2022-11-04T08:55:56.300    10205: 19534: 19594 E/AndroidRuntime  ] FATAL EXCEPTION: Thread-7
Process: com.eg.android.AlipayGphone:widgetProvider, PID: 19534
java.lang.IllegalArgumentException: Service not registered: bw0@e909668
	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1917)
	at android.app.ContextImpl.unbindService(ContextImpl.java:2030)
	at android.content.ContextWrapper.unbindService(ContextWrapper.java:856)
	at android.content.ContextWrapper.unbindService(ContextWrapper.java:856)
	at xi0.a(chromium-TrichromeWebViewGoogle6432.aab-stable-524912634:30)
	at Zv0.run(chromium-TrichromeWebViewGoogle6432.aab-stable-524912634:256)
	at java.lang.Thread.run(Thread.java:920)
[ 2022-11-04T08:56:12.253    10212: 19847: 19847 I/LSPosed         ] Loading xposed for com.coolapk.market/10212
[ 2022-11-04T08:56:12.257    10212: 19847: 19847 I/LSPosed-Bridge  ] Loading module org.hello.coolapk from /data/app/~~pb-XtZYA59nF5Vz1YS4K-w==/org.hello.coolapk-MQZTRrSfyAijH9IyTC4ehg==/base.apk
[ 2022-11-04T08:56:12.270    10212: 19847: 19847 I/LSPosed-Bridge  ]   Loading class org.fuck.coolapk.XposedEntry
[ 2022-11-04T08:56:13.476    10212: 19847: 19847 I/LSPosed-Bridge  ] FuckCoolApk: {removeBottomNavigationItems=false, bannerAuto=true, wlimits=v1RnVja0Nvb2xhcGtSXTAxd2pOQHJjfkB5THN1NHwkMmEkMTAkNmMxY2Y4OGNmN2M5ZWI2ZjY1YzYwdUNERnFENUxRVzFXNGEuZGF6VFl3OHJLLkcwYng3eEN8TkRJNE1UZzVOalV5TkRZek16azJPUT09, removeBannerAds=true, bannerUrl=https://316.coolapk1s.com, customCard=, removeFeedAdsEnhance=true, disableUmeng=true, bannerPic=https://cdn.jsdelivr.net/gh/ejiaogl/FuckCoolapk@master/art/316/316-2.png, removeFeedAds=true, disableBugly=true, removeSearchActivityItemHotSearchListCard=true, redirectLink=www.coolapk.com, timestamp=1667523032, checkFeedStatus=true, bannerForced=false, removeSearchActivityItemHotSearch=true, removeBottomNavigationDiscovery=false, removeSearchBoxHotWord=true, bannerEnable=true, removeFeedGoods=true, removeShareLinkParams=true, modifyShareUrl=false, removeUpdateDialog=true}
[ 2022-11-04T08:56:14.186    10212: 19847: 19847 I/LSPosed-Bridge  ] FuckCoolApk: CustomRuleConfig.getAll() theList = [CustomRule(entityType=null, title=小游戏, extraData=null, url=https://www.coolapk.com/link/sdw?sdw_simple=, entityTemplate=null, entities=null), CustomRule(entityType=null, title=双11, extraData=null, url=/feed/40241528, entityTemplate=null, entities=null), CustomRule(entityType=null, title=冲锋衣, extraData=null, url=/feed/40355595, entityTemplate=null, entities=null)]
[ 2022-11-04T08:56:14.197    10212: 19847: 19847 I/LSPosed-Bridge  ] FuckCoolApk: Class BeiZi not found
[ 2022-11-04T08:56:14.197    10212: 19847: 19847 I/LSPosed-Bridge  ] FuckCoolApk: Class BeiZis not found
[ 2022-11-04T08:56:14.407    10212: 19847: 19847 I/LSPosed-Bridge  ] FuckCoolApk: DexKit CheckUpdateMethod found: com.coolapk.market.CoolMarketApplication.ށ
[ 2022-11-04T08:56:14.453    10212: 19847: 19847 I/LSPosed-Bridge  ] FuckCoolApk: DexKit FeedBuildDialogMethod found: ז.ވ.Ԫ
[ 2022-11-04T08:56:14.497    10212: 19847: 19847 I/LSPosed-Bridge  ] FuckCoolApk: DexKit ReplyBuildDialogMethod found: ࡅ.ؠ.Ԩ
[ 2022-11-04T08:56:14.504    10212: 19847: 19847 I/LSPosed-Bridge  ] FuckCoolApk: rough_draft_backups path: /storage/emulated/0/Android/data/com.coolapk.market/files/rough_draft_backups
[ 2022-11-04T08:56:14.506    10212: 19847: 19847 I/LSPosed-Bridge  ] FuckCoolApk: rough draft listener started

**Comment by a1029602653** [comment]
我也出现了这个问题，气的我直接卸载酷安

**Comment by lz233** [comment]
应该是酷安加了双十一的广告导致的（

**Comment by qqlittleice233** [comment]
广告过滤器在测试，如果这个问题太严重的话可能会考虑回退以前的版本
