### ISSUE TITLE
使用过程中闪退

### ISSUE THREAD

**Issue by Mubai-meng** [Xposed-Modules-Repo/org.hello.coolapk#9]
使用环境：安卓12，lsp，coolapk12.5
模块版本：1.16（1152）
===============
[Device Brand]: samsung
[Device Model]: SM-G9910
[Display]: SP1A.210812.016.G9910ZCS2CVI4
[Android Version]: 12
[API Version]: 31
[System Locale]: zh_CN_#Hans
[Package Name]: com.coolapk.market
[Error Type]: Jvm
[Crash Time]: 2022-10-31T08:57:17.503
[Stack Trace]:
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.get(ArrayList.java:437)
	at Τ.ၵ.ވ(ItemPodiumViewHolder.kt:5)
	at ذ.Ԫ.Ԩ(BindingViewHolderFactor.kt:2)
	at ذ.ނ$Ϳ.Ԩ(SimpleViewHolderFactor.kt:2)
	at ذ.Ϳ.Ԫ(BaseMultiTypeAdapter.kt:1)
	at ذ.Ϳ.onBindViewHolder(BaseMultiTypeAdapter.kt:2)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:1)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:8)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:7)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:55)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:2)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:3)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:65)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:3)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:18)
	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:792)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by qqlittleice233** [comment]
广告过滤器在测试，如果这个问题太严重的话可能会考虑回退以前的版本
